Repository playkuround/playkuround-server, pull requests merged in 2022-09, with the labels that each got.

#10 랭킹 API 구현
  src/main/java/com/playkuround/playkuroundserver/domain/ranking/api/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/ranking/api/RankingApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/ranking/application/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/ranking/application/RankingService.java
  src/main/java/com/playkuround/playkuroundserver/domain/ranking/dao/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/api/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/application/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/application/ScoreService.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/dao/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/dao/ScoreRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/domain/Score.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/dto/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/dto/ScoreRankingDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/exception/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/score/exception/ScoreNotFoundException.java
Labels: enhancement

#12 학과 Enum 추가 및 EnumValidator 수정
  src/main/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/application/ScoreService.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/dto/ScoreRegisterDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/domain/Major.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/dto/UserRegisterDto.java
  src/main/java/com/playkuround/playkuroundserver/global/validation/EnumValidator.java
  src/main/java/com/playkuround/playkuroundserver/global/validation/ValidEnum.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/ScoreApiTest.java
Labels: enhancement

#13 인증 메일 전송 및 인증코드 일치 확인 API 구현
  build.gradle
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dto/ResponseFindAdventure.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/application/AttendanceSearchService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/dao/AttendanceRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/api/AuthEmailApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailSendService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailVerifyService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dao/AuthEmailRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/domain/AuthEmail.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dto/AuthEmailSendDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/exception/AuthCodeExpiredException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/exception/AuthEmailNotFoundException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/exception/NotKUEmailException.java
  src/main/java/com/playkuround/playkuroundserver/domain/common/BaseTimeEntity.java
  src/main/java/com/playkuround/playkuroundserver/global/config/WebConfig.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
  src/main/java/com/playkuround/playkuroundserver/infra/email/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/infra/email/EmailService.java
  src/main/java/com/playkuround/playkuroundserver/infra/email/exception/EmailSendFailException.java
  src/main/resources/application.yml
Labels: enhancement

#14 Feature/adventure
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dto/RequestSaveAdventure.java
  src/main/java/com/playkuround/playkuroundserver/global/util/LocationDistanceUtils.java
Labels: enhancement

#15 토큰 만료 관련 로직 수정
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/RefreshTokenValidator.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenManager.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
  src/main/java/com/playkuround/playkuroundserver/global/interceptor/AuthenticationInterceptor.java
  src/main/resources/application.yml
Labels: enhancement

#16 LocationUtils 클래스 static 객체 초기화 방식 변경
  src/main/java/com/playkuround/playkuroundserver/global/util/LocationUtils.java
Labels: enhancement

#20 인증 메일 전송 횟수 제한
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/api/AuthEmailApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailSendService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailVerifyService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dao/AuthEmailRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dto/AuthEmailSendDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/AuthCodeExpiredException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/AuthEmailNotFoundException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/NotKUEmailException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/SendingLimitExceededException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
Labels: enhancement

#21 workflow main.yml name 변경
  .DS_Store
  .github/.DS_Store
  .github/workflows/main.yml
Labels: ci/cd

#19 현재 위치 기준 10m 내에 있는 랜드마크 반환 api
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dto/ResponseFindAdventure.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/api/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkFindNearService.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkInitDb.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/dao/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/domain/GameType.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/domain/Landmark.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/dto/.gitkeep
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/dto/FindNearLandmark.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApi.java
  src/main/java/com/playkuround/playkuroundserver/global/validation/Latitude.java
  src/main/java/com/playkuround/playkuroundserver/global/validation/Longitude.java
  src/main/resources/application-test.yml
  src/main/resources/data-h2.sql
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApiTest.java
Labels: enhancement

#22 Test/landmark
  .gitignore
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApiTest.java
Labels: bug
