Repository playkuround/playkuround-server, pull requests merged in 2023-03, with the labels that each got.

#41 리팩토링
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/exception/DuplicateAdventureException.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/exception/InvalidLandmarkLocationException.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/exception/DuplicateAttendanceException.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/exception/InvalidAttendanceLocationException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/AuthCodeExpiredException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/NotKUEmailException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/NotMatchAuthCodeException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/SendingLimitExceededException.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/RefreshTokenValidator.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenManager.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/exception/InvalidTokenException.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/domain/BadgeType.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/exception/BadgeTypeNotFoundException.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/exception/ScoreTypeNotMatchException.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/exception/UserEmailDuplicationException.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/exception/UserNicknameDuplicationException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/ErrorCode.java
  src/main/java/com/playkuround/playkuroundserver/global/error/ErrorResponse.java
  src/main/java/com/playkuround/playkuroundserver/global/error/GlobalExceptionHandler.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/AuthenticationException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/BusinessException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/EntityNotFoundException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/InvalidLocationException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/InvalidValueException.java
  src/main/java/com/playkuround/playkuroundserver/global/interceptor/AuthenticationInterceptor.java
  src/main/java/com/playkuround/playkuroundserver/infra/email/exception/EmailSendFailException.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
Labels: refactor

#42 리팩토링
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/application/AttendanceRegisterService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/application/AttendanceSearchService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/domain/Attendance.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/dto/AttendanceRegisterDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailVerifyService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/dao/RefreshTokenRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/domain/RefreshToken.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/api/BadgeApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/application/BadgeService.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/application/ScoreService.java
  src/main/java/com/playkuround/playkuroundserver/domain/score/domain/ScoreType.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/api/UserApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserLoginService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserLogoutService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserProfileService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserRegisterService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserValidator.java
  src/main/java/com/playkuround/playkuroundserver/global/common/response/ApiResponse.java
  src/main/java/com/playkuround/playkuroundserver/global/resolver/UserEmailArgumentResolver.java
  src/main/java/com/playkuround/playkuroundserver/global/resolver/UserEntity.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/badge/api/BadgeApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApiTest.java
Labels: refactor

#44 feat: 리프레시 토큰 조회 클래스 추가
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/dao/RefreshTokenFindDao.java
Labels: feature

#45 리프레시 엔티티 조회 exception 추가
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/exception/RefreshTokenNotFoundException.java
Labels: feature

#46 빈 리스트와 INIT 타입의 스코어 추가함으로 인한 변경
  src/test/java/com/playkuround/playkuroundserver/domain/badge/api/BadgeApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/score/api/ScoreApiTest.java
Labels: refactor

#47 레디스 주소 변경
  src/main/resources/application.yml
Labels: refactor

#48 redis 비밀번호 설정
  src/main/resources/application.yml
Labels: feature

#49 Update
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dao/AdventureRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/domain/BadgeType.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkFindNearService.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/domain/Landmark.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/dto/FindNearLandmark.java
  src/main/resources/data-h2.sql
  src/main/resources/data-mysql.sql
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApiTest.java
Labels: feature

#50 release
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dao/AdventureRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/domain/BadgeType.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkFindNearService.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/domain/Landmark.java
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/dto/FindNearLandmark.java
  src/main/resources/data-h2.sql
  src/main/resources/data-mysql.sql
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/landmark/api/LandmarkApiTest.java
Labels: release

#51 Update
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkFindNearService.java
  src/main/resources/application.yml
Labels: feature

#52 release
  src/main/java/com/playkuround/playkuroundserver/domain/landmark/application/LandmarkFindNearService.java
  src/main/resources/application.yml
Labels: release

#53 출석, 탐험 시 자동으로 배지가 저장되도록 변경
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/application/AttendanceRegisterService.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApiTest.java
Labels: feature

#54 release
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/attendance/application/AttendanceRegisterService.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
  src/test/java/com/playkuround/playkuroundserver/domain/attendance/api/AttendanceApiTest.java
Labels: release
