Repository playkuround/playkuround-server, pull requests merged in 2023-02, with the labels that each got.

#36 Feature/adventure
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dao/AdventureRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/exception/DuplicateAdventureException.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/domain/BadgeType.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
Labels: feature

#37 merge to main branch
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/application/AdventureService.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/dao/AdventureRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/adventure/exception/DuplicateAdventureException.java
  src/main/java/com/playkuround/playkuroundserver/domain/badge/domain/BadgeType.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
  src/test/java/com/playkuround/playkuroundserver/domain/adventure/api/AdventureApiTest.java
Labels: release

#38 Feature/auth
  README.md
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/api/AuthEmailApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailVerifyService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dto/AuthVerifyEmailDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/NotMatchAuthCodeException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
Labels: feature

#39 Develop
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/api/AuthEmailApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/application/AuthEmailVerifyService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/dto/AuthVerifyEmailDto.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/email/exception/NotMatchAuthCodeException.java
  src/main/java/com/playkuround/playkuroundserver/global/error/exception/ErrorCode.java
Labels: release

#40 리프레시 토큰 레디스로 관리하도록 변경
  build.gradle
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/api/TokenApi.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenIssueService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenManager.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/application/TokenService.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/dao/RefreshTokenRepository.java
  src/main/java/com/playkuround/playkuroundserver/domain/auth/token/domain/RefreshToken.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserLoginService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserLogoutService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/application/UserRegisterService.java
  src/main/java/com/playkuround/playkuroundserver/domain/user/domain/User.java
  src/main/resources/application.yml
Labels: refactor
